[package]
name = "uniqopy"
version = "0.2.0"
edition = "2021"
authors = ["Nathaniel Knight <nathaniel.ep@gmail.com>"]
license-file = "LICENSE.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
md5 = "0.7.0"
